print("**************Details of students********************")
name=input("Enter name of student:")
usn=input("Enter usn:")
dept=input("Enter department:")
year=input("Enter year of student:")
sem=input("Enter Semester:")
print("******************************************************")
c1=int(input("Enter marks obtained in course Python programming:"))
c2=int(input("Enter marks obtained in course Digital image processing:"))
c3=int(input("Enter marks obtained in course Embedded system:"))
c4=int(input("Enter marks obtained in course java:"))
c5=int(input("Enter marks obtained in course Python OE:"))

total=(c1+c2+c3+c4+c5)
per=(total/5.0)
print("******************************************************")
print("Name\t\t:"+name)
print("USN\t\t:"+usn)
print("Depatment\t:"+dept)
print("Year\t\t:"+year)
print("Semester\t:"+sem)
print("******************************************************")
print("sr No:\t\t\t\t\Name of cousre:\tmarks:")
print("1.\tPython programming\t\t:",((int)(c1)))
print("2.\tDigital Image processing\t:",((int)(c2)))
print("3.\tEmbedded system\t\t\t:",((int)(c3)))
print("4.\tjava\t\t\t\t:",((int)(c4)))
print("5.\tpython OE\t\t\t:",((int)(c5)))
print("******************************************************")
print("Total Marks\t:",total)
print("Percentage\t:",per)
print("******************************************************")
